### ISSUE TITLE
Repeated execution gives different results with CUDA

### ISSUE THREAD

**Issue by merckxiaan** [JuliaGPU/KernelAbstractions.jl#108]
Running the function here multiple times gives different results.
```julia
using CUDA, KernelAbstractions, Tullio, Flux
a = rand(2,2)|>gpu;
f(x) = @tullio out[m, n] := x[m, i] * softmax(x)[i, n]

[f(a) for _ in 1:20]
```
```
20-element Array{CuArray{Float32,2,Nothing},1}:
 [0.4637492 0.45766857; 0.7698339 1.3491455]
 [0.3343358 0.23584612; 0.55500484 0.6952427]
 [0.2614223 0.3212939; 0.54472876 0.5025235]
 [0.4637492 0.45766857; 0.7698339 1.3491455]
 [0.3343358 0.23584612; 0.55500484 0.6952427]
 [0.4637492 0.45766857; 0.7698339 1.3491455]
 [0.2543268 0.23732993; 0.46905848 0.511475]
 [0.52248245 0.0; 0.6767997 0.0]
 [0.3343358 0.23584612; 0.55500484 0.6952427]
 [0.52248245 0.0; 0.6767997 0.0]
 [0.2614223 0.3212939; 0.54472876 0.5025235]
 [0.4637492 0.45766857; 0.7698339 1.3491455]
 [0.9860959 0.0; 1.7307466 0.0]
 [0.52248245 0.0; 0.6767997 0.0]
 [0.3343358 0.23584612; 0.55500484 0.6952427]
 [0.0 0.0; 0.0 0.0]
 [0.3343358 0.23584612; 0.55500484 0.6952427]
 [0.2614223 0.3212939; 0.54472876 0.5025235]
 [0.4637492 0.45766857; 0.7698339 1.3491455]
 [0.4637492 0.45766857; 0.7698339 1.3491455]
```
Forcing Tullio to run KA's code on cpu (by setting `threads=false`) doesn't yield this behaviour so the issue might be in KernelAbstractions.
Michael Abbott wasn't able to reproduce but he provided the code to generated Tullio code:
```julia
julia> using TensorCast # for my variant of @macroexpand1
julia> @pretty @tullio out[m, n] := x[m, i] * softmax(x)[i, n] grad=false
out = let
        ndims(x) == 2 || error("expected a 2-array x")
        local var"≪softmax(x)≫" = softmax(x)
        ndims(var"≪softmax(x)≫") == 2 || error("expected a 2-array ≪softmax(x)≫")
        begin
            local function 𝒜𝒸𝓉!(::Type, ℛ::AbstractArray{𝒯}, x, var"≪softmax(x)≫", 𝒶𝓍m, 𝒶𝓍n, 𝒶𝓍i, ♻ = nothing) where 𝒯
                    @inbounds @fastmath(begin
                                nothing
                                for n in 𝒶𝓍n
                                    for m in 𝒶𝓍m
                                        begin
                                            𝒜𝒸𝒸 = ifelse(isnothing(♻), zero(𝒯), ℛ[m, n])
                                            for i in 𝒶𝓍i
                                                𝒜𝒸𝒸 = 𝒜𝒸𝒸 + x[m, i] * var"≪softmax(x)≫"[i, n]
                                            end
                                            ℛ[m, n] = 𝒜𝒸𝒸
                                        end
                                    end
                                end
                            end)
                end
        end
        begin
            begin
                function jay(ℛ::AbstractArray{𝒯}, x, var"≪softmax(x)≫", 𝒶𝓍m, 𝒶𝓍n, 𝒶𝓍i, ♻; ) where 𝒯
                    let
                        $(Expr(:aliasscope))
                        for zebra in (KernelAbstractions.__workitems_iterspace)()
                            (KernelAbstractions.__validindex)(zebra) || continue
                            (m, n) = __index_Global_NTuple(zebra)
                            begin
                                nothing
                                𝒜𝒸𝒸 = ifelse(isnothing(♻), zero(𝒯), ℛ[m, n])
                                for i in 𝒶𝓍i
                                    𝒜𝒸𝒸 = 𝒜𝒸𝒸 + x[m, i] * var"≪softmax(x)≫"[i, n]
                                end
                                ℛ[m, n] = 𝒜𝒸𝒸
                            end
                        end
                        $(Expr(:popaliasscope))
                        return nothing
                    end
                end
```
[zulip conversation](https://julialang.zulipchat.com/#narrow/stream/238249-machine-learning/topic/Automatic.20batching/near/202982014)

lastly here's my versioninfo and pkg status:
```
versioninfo()
Julia Version 1.4.1
Commit 381693d3df* (2020-04-14 17:20 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
Environment:
  JULIA = C:\Users\jules\AppData\Local\Programs\Julia\Julia-1.4.1\bin\julia.exe
```
```
pkg> st
Status `D:\code\Transformer\Project.toml`
  [052768ef] CUDA v1.0.2
  [587475ba] Flux v0.11.0-DEV #master (https://github.com/FluxML/Flux.jl.git)
  [63c18a36] KernelAbstractions v0.3.0
  [295af30f] Revise v2.7.3
  [899adc3e] TensorBoardLogger v0.1.10
  [bc48ee85] Tullio v0.1.2
  [e88e6eb3] Zygote v0.5.2
```
Thanks,
Jules

**Comment by mcabbott** [comment]
Note that I can't reproduce this on my machine, with the same packages (and Julia 1.4.2). I reliably get the expected answer, `f(a) ≈ a * softmax(a)`

If it would help I can dig out the exact code, before expanding `@kernel` etc. as above.

**Comment by merckxiaan** [comment]
To add to this, I recently purchased a new laptop and succeeded in reproducing this issue by running the original MWE.

Swapping `softmax` with another vector->vector function such as `Flux.normalise` keeps the issue.
It doesn't happen with all vector->vector functions though (e.g. `g(x) = x./sum(x)` runs just fine)

I'm really curious as to what's going here but the underlying machinery goes way over my head.

**Comment by MasonProtter** [comment]
I cannot reproduce:
```julia
julia> using CUDA, KernelAbstractions, Tullio, Flux
[ Info: Precompiling CUDA [052768ef-5323-5732-b1bb-66c8b64840ba]
[ Info: Precompiling KernelAbstractions [63c18a36-062a-441e-b654-da1e3ab1ce7c]
[ Info: Precompiling Tullio [bc48ee85-29a4-5162-ae0b-a64e1601d4bc]
[ Info: Precompiling Flux [587475ba-b771-5e3f-ad9e-33799f191a9c]

julia> a = rand(2,2)|>gpu;

julia> f(x) = @tullio out[m, n] := x[m, i] * softmax(x)[i, n]
f (generic function with 1 method)

julia> [f(a) for _ in 1:20]
20-element Array{CuArray{Float32,2},1}:
 [0.38549656 0.4023041; 0.6426005 0.6706107]
 [0.38549656 0.4023041; 0.6426005 0.6706107]
 [0.38549656 0.4023041; 0.6426005 0.6706107]
 [0.38549656 0.4023041; 0.6426005 0.6706107]
 [0.38549656 0.4023041; 0.6426005 0.6706107]
 [0.38549656 0.4023041; 0.6426005 0.6706107]
 [0.38549656 0.4023041; 0.6426005 0.6706107]
 [0.38549656 0.4023041; 0.6426005 0.6706107]
 [0.38549656 0.4023041; 0.6426005 0.6706107]
 [0.38549656 0.4023041; 0.6426005 0.6706107]
 [0.38549656 0.4023041; 0.6426005 0.6706107]
 [0.38549656 0.4023041; 0.6426005 0.6706107]
 [0.38549656 0.4023041; 0.6426005 0.6706107]
 [0.38549656 0.4023041; 0.6426005 0.6706107]
 [0.38549656 0.4023041; 0.6426005 0.6706107]
 [0.38549656 0.4023041; 0.6426005 0.6706107]
 [0.38549656 0.4023041; 0.6426005 0.6706107]
 [0.38549656 0.4023041; 0.6426005 0.6706107]
 [0.38549656 0.4023041; 0.6426005 0.6706107]
 [0.38549656 0.4023041; 0.6426005 0.6706107]
```

**Comment by merckxiaan** [comment]
Thanks a lot for also taking a look Mason.
I installed Julia 1.5 to check whether that made a difference for me but it doesn't.
```julia
julia> using CUDA, KernelAbstractions, Tullio, Flux

julia> a = rand(2,2)|>gpu;

julia> f(x) = @tullio out[m, n] := x[m, i] * softmax(x)[i, n]
f (generic function with 1 method)

julia> [f(a) for _ in 1:20]
20-element Array{CuArray{Float32,2},1}:
 [0.31156603 0.31306198; 0.37330347 0.5727489]
 [0.0 0.0; 0.0 0.0]
 [0.0 0.0; 0.0 0.0]
 [0.0 0.0; 0.0 0.0]
 [0.0 0.0; 0.0 0.0]
 [0.0 0.0; 0.0 0.0]
 [0.0 0.0; 0.0 0.0]
 [0.0 0.0; 0.0 0.0]
 [0.0 0.0; 0.0 0.0]
 [0.0 0.0; 0.0 0.0]
 [0.0 0.0; 0.0 0.0]
 [0.0 0.0; 0.0 0.0]
 [0.0 0.0; 0.0 0.0]
 [0.0 0.0; 0.0 0.0]
 [0.0 0.0; 0.0 0.0]
 [0.0 0.0; 0.0 0.0]
 [0.0 0.0; 0.0 0.0]
 [0.0 0.0; 0.0 0.0]
 [0.0 0.0; 0.0 0.0]
 [0.0 0.0; 0.0 0.0]
```
This is a different pc than for the original post.

```
(@v1.5) pkg> st
Status `C:\Users\jules\.julia\environments\v1.5\Project.toml`
  [052768ef] CUDA v1.3.3
  [587475ba] Flux v0.11.1
  [63c18a36] KernelAbstractions v0.3.3
  [bc48ee85] Tullio v0.2.5

julia> versioninfo()
Julia Version 1.5.1
Commit 697e782ab8 (2020-08-25 20:08 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)

julia> CUDA.versioninfo()
CUDA toolkit 11.0.3, artifact installation
CUDA driver 11.0.0
NVIDIA driver 452.6.0

Libraries:
- CUBLAS: 11.2.0
- CURAND: 10.2.1
- CUFFT: 10.2.1
- CUSOLVER: 10.6.0
- CUSPARSE: 11.1.1
- CUPTI: 13.0.0
- NVML: 11.0.0+452.6
- CUDNN: 8.0.2 (for CUDA 11.0.0)
- CUTENSOR: 1.2.0 (for CUDA 11.0.0)

Toolchain:
- Julia: 1.5.1
- LLVM: 9.0.1
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4
- Device support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75

1 device:
  0: GeForce RTX 2070 with Max-Q Design (sm_75, 7.843 GiB / 8.000 GiB available)
```
I'm having a hard time believing I would be doing something wrong here as there's not much to do wrong.
The one thing that's different is the CUDA version, I'm wondering whether there's a way to downgrade my CUDA install using the artifact system?

**Comment by merckxiaan** [comment]
Ok, I tried with CUDA 10:
```
CUDA toolkit 10.2.89, artifact installation
CUDA driver 11.0.0
NVIDIA driver 452.6.0

Libraries:
- CUBLAS: 10.2.2
- CURAND: 10.1.2
- CUFFT: 10.1.2
- CUSOLVER: 10.3.0
- CUSPARSE: 10.3.1
- CUPTI: 12.0.0
- NVML: 11.0.0+452.6
- CUDNN: 8.0.2 (for CUDA 10.2.0)
- CUTENSOR: 1.2.0 (for CUDA 10.2.0)

Toolchain:
- Julia: 1.5.1
- LLVM: 9.0.1
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4
- Device support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75

Environment:
- JULIA_CUDA_VERSION: 10.2

1 device:
  0: GeForce RTX 2070 with Max-Q Design (sm_75, 7.750 GiB / 8.000 GiB available)
```
but I still get the issue, I feel like I'm slowly losing my mind...

**Comment by mcabbott** [comment]
No great ideas, but what happens if you compute `softmax(x)` outside? (It is pulled out of the loops, but perhaps there's some weird scope issue, or some weird non-ascii symbol issue.) Or define your own trivial function which calls `NNlib.softmax`, and has the same or a different name?

**Comment by vchuravy** [comment]
So when is Tullio calling `wait` on the KA kernel and how is it dealing with CUDA.jl code being run?

**Comment by mcabbott** [comment]
It calls wait immediately. 

I'm not sure what you mean by "dealing with". There is a method which is loaded using Requires.jl, so that `::CuArray` skips the thread-handling routine and calls the function `𝒜𝒸𝓉!` immediately, just once on the whole array. But otherwise there is no direct interaction with CUDA.jl.

Here's a prettier version of the code it generates, before expanding `@kernel`.
```julia
julia> @tullio out[m, n] := x[m, i] * softmax(x)[i, n] verbose=2
┌ Info: >>>>> Preliminary expressions
│   verbosetidy(ex_pre) =
│    quote
│        ndims(x) == 2 || throw("expected a 2-array x")
│        local var"≪softmax(x)≫" = softmax(x)
│        ndims(var"≪softmax(x)≫") == 2 || throw("expected a 2-array ≪softmax(x)≫")
└    end
┌ Info: ===== Base actor 
│   verbosetidy(ex_act) =
│    quote
│        local @inline(function 𝒜𝒸𝓉!(::Type, ℛ::AbstractArray{𝒯}, x, var"≪softmax(x)≫", 𝒶𝓍m, 𝒶𝓍n, 𝒶𝓍i, ♻️ = nothing, 💀 = true) where 𝒯
│                    @inbounds @fastmath(begin
│                                for n = 𝒶𝓍n
│                                    for m = 𝒶𝓍m
│                                        𝒜𝒸𝒸 = if isnothing(♻️)
│                                                zero(𝒯)
│                                            else
│                                                ℛ[m, n]
│                                            end
│                                        for i = 𝒶𝓍i
│                                            𝒜𝒸𝒸 = 𝒜𝒸𝒸 + x[m, i] * var"≪softmax(x)≫"[i, n]
│                                        end
│                                        ℛ[m, n] = 𝒜𝒸𝒸
│                                    end
│                                end
│                            end)
│                end)
└    end
┌ Info: =====KA===== KernelAbstractions kernel 
│   verbosetidy(kex1) =
│    quote
│        KernelAbstractions.@kernel function var"##🇨🇺#253"(ℛ::AbstractArray{𝒯}, x, var"≪softmax(x)≫", 𝒶𝓍m, 𝒶𝓍n, 𝒶𝓍i, ♻️, 💀) where 𝒯
│                (m, n) = @index(Global, NTuple)
│                begin
│                    𝒜𝒸𝒸 = if isnothing(♻️)
│                            zero(𝒯)
│                        else
│                            ℛ[m, n]
│                        end
│                    for i = 𝒶𝓍i
│                        𝒜𝒸𝒸 = 𝒜𝒸𝒸 + x[m, i] * var"≪softmax(x)≫"[i, n]
│                    end
│                    ℛ[m, n] = 𝒜𝒸𝒸
│                end
│            end
└    end
┌ Info: =====KA===== KernelAbstractions CUDA actor 
│   verbosetidy(kex2) =
│    quote
│        local @inline(function 𝒜𝒸𝓉!(::Type{<:CuArray}, ℛ::AbstractArray{𝒯}, x, var"≪softmax(x)≫", 𝒶𝓍m, 𝒶𝓍n, 𝒶𝓍i, ♻️ = nothing, 💀 = true) where 𝒯
│                    @info "running KernelAbstractions + CUDA actor " maxlog = 3 _id = 0xd6dfd2bd8bf88995
│                    cu_kern! = var"##🇨🇺#253"(CUDADevice(), 256)
│                    first(𝒶𝓍m) == 1 || throw("KernelAbstractions can't handle OffsetArrays here")
│                    first(𝒶𝓍n) == 1 || throw("KernelAbstractions can't handle OffsetArrays here")
│                    𝒜𝒸𝒸 = cu_kern!(ℛ::AbstractArray{𝒯}, x, var"≪softmax(x)≫", 𝒶𝓍m, 𝒶𝓍n, 𝒶𝓍i, ♻️, 💀; ndrange = tuple(length(𝒶𝓍m), length(𝒶𝓍n)))
│                    KernelAbstractions.wait(𝒜𝒸𝒸)
│                end)
└    end
```

**Comment by vchuravy** [comment]
You are missing a dependency edge.
 `│                    𝒜𝒸𝒸 = cu_kern!(ℛ::AbstractArray{𝒯}, x, var"≪softmax(x)≫", 𝒶𝓍m, 𝒶𝓍n, 𝒶𝓍i, ♻️, 💀; ndrange = tuple(length(𝒶𝓍m), length(𝒶𝓍n)))`

needs to be:

`│                    𝒜𝒸𝒸 = cu_kern!(ℛ::AbstractArray{𝒯}, x, var"≪softmax(x)≫", 𝒶𝓍m, 𝒶𝓍n, 𝒶𝓍i, ♻️, 💀; ndrange = tuple(length(𝒶𝓍m), length(𝒶𝓍n)), dependencies=Event(CuDevice()))`

and you might want to consider (for better performance) to switch:

`│                    KernelAbstractions.wait(𝒜𝒸𝒸)`

to
`│                    KernelAbstractions.wait(CuDevice(), 𝒜𝒸𝒸)`

What you are seeing is that CUDA.jl kernels are allowed to concurrently with KA. So you need to be defensive against that and add a synchronization edge on the CuDefaultStream, causing all KA kernels to wait on CUDA.jl kernels to finish.

**Comment by mcabbott** [comment]
Great, thank you. 

I've added these things at https://github.com/mcabbott/Tullio.jl/pull/32, but haven't tried them out as something is wrong with that computer. But perhaps @merckxiaan can try this out?

**Comment by merckxiaan** [comment]
Not sure whether I should reply here but running the MWE on that branch gives the following error.
```julia
julia> [f(a) for _ in 1:20]
ERROR: MethodError: no method matching CuDevice()
Closest candidates are:
  CuDevice(::Type{Bool}, ::Int32) at C:\Users\jules\.julia\packages\CUDA\dZvbp\lib\cudadrv\devices.jl:17
  CuDevice(::Integer) at C:\Users\jules\.julia\packages\CUDA\dZvbp\lib\cudadrv\devices.jl:23
  CuDevice(::CuContext) at C:\Users\jules\.julia\packages\CUDA\dZvbp\lib\cudadrv\context.jl:157
Stacktrace:
 [1] ���! at C:\Users\jules\.julia\packages\Tullio\Dlm6Z\src\macro.jl:1000 [inlined]
 [2] ���! at C:\Users\jules\.julia\packages\Tullio\Dlm6Z\src\macro.jl:997 [inlined]
 [3] threader(::var"#���!#1", ::Type{CuArray{Float32,2}}, ::CuArray{Float32,2}, ::Tuple{CuArray{Float32,2},CuArray{Float32,2}}, ::Tuple{Base.OneTo{Int64},Base.OneTo{Int64}}, ::Tuple{Base.OneTo{Int64}}, ::Function, ::Int64, ::Nothing) at C:\Users\jules\.julia\packages\Tullio\Dlm6Z\src\eval.jl:89
 [4] (::var"#ℳ��ℯ#10"{var"#���!#1"})(::CuArray{Float32,2}, ::CuArray{Float32,2}) at C:\Users\jules\.julia\packages\Tullio\Dlm6Z\src\macro.jl:802
 [5] (::Tullio.Eval{var"#ℳ��ℯ#10"{var"#���!#1"},var"#265#∇ℳ��ℯ#9"{var"#∇���!#5"}})(::CuArray{Float32,2}, ::Vararg{CuArray{Float32,2},N} where N) at C:\Users\jules\.julia\packages\Tullio\Dlm6Z\src\eval.jl:20
 [6] f(::CuArray{Float32,2}) at .\REPL[7]:1
 [7] (::var"#12#13")(::Int64) at .\none:0
 [8] iterate at .\generator.jl:47 [inlined]
 [9] collect(::Base.Generator{UnitRange{Int64},var"#12#13"}) at .\array.jl:686
 [10] top-level scope at REPL[8]:1
```

**Comment by merckxiaan** [comment]
This is now fixed in Tullio and this issue can be closed.
Thanks vchuravy and mcabbott!
